version: '2'

networks:
  lensgui_network:
    external:
      name: nginxproxynetwork

services:

  esta:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: esta_app
    restart: always
    environment:
      - VIRTUAL_HOST=lensgui.sd.di.huc.knaw.nl
    ports:
      - 8084:80
    networks:
      - lensegui_network