version: '2'

networks:
  lensgui_network:
    external:
      name: nginxproxynetwork

services:
  lensgui:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lens_app
    restart: always
    environment:
      - VIRTUAL_HOST=lensgui.sd.di.huc.knaw.nl
    networks:
      - lensgui_network